export const AssetConfig = {
    images: [
        { key: 'clouds', path: 'game/assets/images/clouds.jpg' },
        { key: 'darkgreen', path: 'game/assets/images/darkgreen.png' },
        { key: 'green', path: 'game/assets/images/green.png' },
        { key: 'bullet', path: 'game/assets/images/bullet.png' },
        { key: 'mariotiles', path: 'game/assets/images/mariotiles.png' },
        { key: 'fireball', path: 'game/assets/images/fireball-small.png' },
        { key: 'coins', path: 'game/assets/images/coin_new.png' },
        { key: 'platform', path: 'game/assets/images/platformneu.png' },
        { key: 'flag', path: 'game/assets/images/flagneu.png' },
        { key: 'landscape-icon', path: 'game/assets/images/mobile_landscape_icon_v2.png' },
        { key: 'redparticle', path: 'game/assets/images/red.png' },
        { key: 'greenparticle', path: 'game/assets/images/greenball.png' },
        { key: 'orangeparticle', path: 'game/assets/images/orange.png' },
        { key: 'whiteparticle', path: 'game/assets/images/white.png' },
        // Buttons
        { key: 'fullscreenbutton', path: 'game/assets/images/buttons/fullscreen_button_small.png' },
        { key: 'firebutton', path: 'game/assets/images/buttons/fire_button_2.png' },
        { key: 'settingsbutton', path: 'game/assets/images/buttons/settings_button_small.png' },
        { key: 'leftbutton', path: 'game/assets/images/buttons/left_button.png' },
        { key: 'rightbutton', path: 'game/assets/images/buttons/right_button.png' },
        { key: 'reloadbutton', path: 'game/assets/images/buttons/reload_button_small.png' },
        { key: 'menubutton', path: 'game/assets/images/buttons/menue_button_small.png' },
        { key: 'jumpbutton', path: 'game/assets/images/buttons/jump_button_2.png' },
    ],
    audio: [
        { key: 'jumpsound', path: 'game/assets/music/jumpnew.ogg' },
        { key: 'coinsound', path: 'game/assets/music/coinnew.ogg' },
        { key: 'theme', path: 'game/assets/music/mariothemenew.ogg' },
        { key: 'lose', path: 'game/assets/music/losenew.ogg' },
        { key: 'clear', path: 'game/assets/music/stageclearnew.ogg' },
        { key: 'kick', path: 'game/assets/music/kicknew.ogg' },
        { key: 'fireball', path: 'game/assets/music/fireballnew.ogg' },
        { key: 'savepoint', path: 'game/assets/music/savepointnew.ogg' },
        { key: 'pop', path: 'game/assets/music/bulletpopnew.ogg' },
    ],
    spritesheets: [
        { key: 'button', path: 'game/assets/spritesheets/levelbutton.png', frameWidth: 64, frameHeight: 64 },
        { key: 'bricks', path: 'game/assets/spritesheets/bricks.png', frameWidth: 32, frameHeight: 32 },
        { key: 'buttons', path: 'game/assets/spritesheets/buttons.png', frameWidth: 64, frameHeight: 64 },
        { key: 'mario', path: 'game/assets/spritesheets/mariospritesheet.png', frameWidth: 50, frameHeight: 50 },
        { key: 'goomba', path: 'game/assets/spritesheets/goombaspritesheet.png', frameWidth: 50, frameHeight: 50 },
        { key: 'platforms', path: 'game/assets/spritesheets/movingplatforms.png', frameWidth: 128, frameHeight: 32 },
    ],
    tilemaps: [
        { key: 'level1', path: 'game/assets/levels/level1.json' },
        { key: 'level2', path: 'game/assets/levels/level2.json' },
        { key: 'level3', path: 'game/assets/levels/level3.json' },
        { key: 'level4', path: 'game/assets/levels/level4.json' },
    ]
};
